services:
  - type: web
    name: hackrx-rag-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    envVars:
      - key: ASTRA_DB_API_ENDPOINT
        fromSecret: true
      - key: ASTRA_DB_APPLICATION_TOKEN
        fromSecret: true
      - key: PERPLEXITY_API_KEY
        fromSecret: true
